// @ts-nocheck
// @ts-ignore
// Placeholder file for connect-rpc service definition.
// In a real scenario, this would be generated by buf.

import {
  CompletionRequest,
  CompletionResponse,
  InlineCompletionRequest,
  InlineCompletionResponse,
} from './language_server_pb';

export const LanguageServerService = {
  typeName: 'neoai.LanguageServerService',
  methods: {
    completion: {
      name: 'Completion',
      I: CompletionRequest,
      O: CompletionResponse,
      kind: 'unary',
    },
    inlineCompletion: {
      name: 'InlineCompletion',
      I: InlineCompletionRequest,
      O: InlineCompletionResponse,
      kind: 'unary',
    },
  },
};
