// @ts-nocheck
// @ts-ignore
// Placeholder file for protobuf messages.
// In a real scenario, this would be generated by buf.

export class CompletionRequest {
    constructor(data: any) {
        Object.assign(this, data);
    }
}

export class CompletionResponse {
    items: any[] = [];
    constructor(data: any) {
        Object.assign(this, data);
        this.items = data.items || [];
    }
}

export class InlineCompletionRequest {
    constructor(data: any) {
        Object.assign(this, data);
    }
}

export class InlineCompletionResponse {
    items: any[] = [];
    constructor(data: any) {
        Object.assign(this, data);
        this.items = data.items || [];
    }
}

// Add other message types as needed
